---
project_id: sctrial
fastqs: "./data/good_cells.csv" # either a path to the folder or a text file with paths
output_dir: "/mnt/BioAdHoc/Groups/vd-vijay/cramirez/amg319/results/mixcr"
job:
  walltime: 02:00:00
  mem: 10gb
  ppn: 1
  nodes: 1
  submit: yes # yes, no, or force
mixcr_jar: /home/ciro/bin/mixcr-2.1.10/mixcr.jar
pipeline: ./
scratch_dir: /mnt/beegfs # location for temporal data storage
...
